### PR TITLE
Combined alterations for application testing

### PR DESCRIPTION
**Pull request by cuboideum**
This pull request joins pull requests #12 and #13 in order to ascertain if they both work upon upload to the application.

### CODE REVIEW

**Comment by kdaveed** [comment]
The custom entry forms for study design execution, data transformation and drawing a conclusion work with the code from **drawingConcFix** branch.

**Comment by cuboideum** [comment]
Elements like specimen collection processes, specimen, assays, data items and data transformations are named after the extension. It would be more desirable to name them after what they are or what they do to facilitate reuse in other extensions.

**Comment by cuboideum** [comment]
Some labels contain the reference 'Fr.AgeEst', others 'FrAgeEst'. A uniform naming convention would be better.

**Comment by cuboideum** [comment]
Some IRIs are very long. It would be preferable to find naming conventions that generate shorter identifier, e.g. by using abbreviations like 'A' and 'DT' instead of 'Assay' and 'DataTransformation'. Labels would help to put a human-readable face to the IRI strings.

**Comment by cuboideum** [comment]
The classes *rdfbones:MinAgeRange* and *rdfbones:MaxAgeRange* suggest a meaning of 'minimum age range' and 'maximum age range'. Probably IRIs like 'MinAge' and 'MaxAge' would be more straightforward.

But this problem should be solved on core ontology level (cf. [RDFBones-O issue #111](https://github.com/RDFBones/RDFBones-O/issues/111)).

**Comment by cuboideum** [comment]
FrAgeEst uses the data property *frageest:hasAgeRange* to add text to instances of *frageest:Conclusion.FrAgeEst*, while FrSexEst uses *frsexest:HasText* to do the same for *frsexest:ConclusionFrSexEst*. The data property for text associated with instances of subclasses of *obo:IAO_0000144 ('Conclusion textual entity')* should be the same for all these instances in order to facilitate implementation.

This problem should be solved on core ontology level.

**Pull request merged**
